/* AssetFlow — Mock ERP dataset + helpers */
const AV_COLORS=['#1B365D','#B87333','#2F3E46','#3d8a80','#5b6b76','#7a5230','#3b6fa0','#8a6d3b'];
function initials(n){return n.split(' ').filter(Boolean).slice(0,2).map(w=>w[0]).join('').toUpperCase();}
function avatarColor(seed){let h=0;for(let i=0;i<seed.length;i++)h=seed.charCodeAt(i)+((h<<5)-h);return AV_COLORS[Math.abs(h)%AV_COLORS.length];}
function money(n){return '$'+n.toLocaleString('en-US');}

const DB = {
  company:{name:'Northwind Industries', plan:'Enterprise'},
  users:{
    admin:{name:'Aarav Mehta',role:'Admin',email:'aarav.mehta@northwind.io',dept:'IT Operations',phone:'+1 415 220 8841'},
    manager:{name:'Priya Sharma',role:'Asset Manager',email:'priya.sharma@northwind.io',dept:'Facilities',phone:'+1 415 220 7734'},
    head:{name:'Daniel Okafor',role:'Department Head',email:'daniel.okafor@northwind.io',dept:'Engineering',phone:'+1 415 220 9910'},
    employee:{name:'Lena Vargas',role:'Employee',email:'lena.vargas@northwind.io',dept:'Design',phone:'+1 415 220 3352'},
  },
  departments:[
    {id:'DPT-01',name:'Engineering',head:'Daniel Okafor',employees:48,assets:132,location:'Building A · Floor 3',budget:820000,status:'Active'},
    {id:'DPT-02',name:'Design',head:'Lena Vargas',employees:22,assets:64,location:'Building A · Floor 2',budget:310000,status:'Active'},
    {id:'DPT-03',name:'Facilities',head:'Priya Sharma',employees:31,assets:210,location:'Building B · Ground',budget:540000,status:'Active'},
    {id:'DPT-04',name:'IT Operations',head:'Aarav Mehta',employees:27,assets:298,location:'Building B · Floor 1',budget:1200000,status:'Active'},
    {id:'DPT-05',name:'Finance',head:'Grace Bennett',employees:19,assets:71,location:'Building A · Floor 4',budget:260000,status:'Active'},
    {id:'DPT-06',name:'Human Resources',head:'Marcus Reid',employees:14,assets:38,location:'Building A · Floor 4',budget:150000,status:'Active'},
    {id:'DPT-07',name:'Sales',head:'Sofia Duarte',employees:53,assets:120,location:'Building C · Floor 2',budget:430000,status:'Active'},
    {id:'DPT-08',name:'Logistics',head:'Owen Clarke',employees:26,assets:174,location:'Warehouse · Bay 4',budget:390000,status:'Archived'},
  ],
  categories:[
    {id:'CAT-01',name:'Laptops & Computers',icon:'laptop',assets:412,depreciation:'25% / yr',lifespan:'4 years',status:'Active'},
    {id:'CAT-02',name:'Monitors & Displays',icon:'columns',assets:288,depreciation:'20% / yr',lifespan:'5 years',status:'Active'},
    {id:'CAT-03',name:'Networking Equipment',icon:'layers',assets:96,depreciation:'15% / yr',lifespan:'7 years',status:'Active'},
    {id:'CAT-04',name:'Office Furniture',icon:'briefcase',assets:534,depreciation:'10% / yr',lifespan:'10 years',status:'Active'},
    {id:'CAT-05',name:'Vehicles',icon:'package',assets:24,depreciation:'18% / yr',lifespan:'8 years',status:'Active'},
    {id:'CAT-06',name:'Lab & Test Equipment',icon:'target',assets:78,depreciation:'22% / yr',lifespan:'6 years',status:'Active'},
    {id:'CAT-07',name:'Mobile Devices',icon:'phone',assets:196,depreciation:'30% / yr',lifespan:'3 years',status:'Active'},
    {id:'CAT-08',name:'AV & Conferencing',icon:'camera',assets:52,depreciation:'20% / yr',lifespan:'5 years',status:'Active'},
  ],
  employees:[
    {id:'EMP-1042',name:'Daniel Okafor',role:'Department Head',dept:'Engineering',email:'daniel.okafor@northwind.io',assets:3,status:'Active',joined:'2019-03-11'},
    {id:'EMP-1088',name:'Lena Vargas',role:'Senior Designer',dept:'Design',email:'lena.vargas@northwind.io',assets:2,status:'Active',joined:'2020-07-22'},
    {id:'EMP-1120',name:'Priya Sharma',role:'Asset Manager',dept:'Facilities',email:'priya.sharma@northwind.io',assets:4,status:'Active',joined:'2018-01-15'},
    {id:'EMP-1201',name:'Aarav Mehta',role:'IT Administrator',dept:'IT Operations',email:'aarav.mehta@northwind.io',assets:5,status:'Active',joined:'2017-09-02'},
    {id:'EMP-1245',name:'Grace Bennett',role:'Finance Lead',dept:'Finance',email:'grace.bennett@northwind.io',assets:2,status:'Active',joined:'2021-02-18'},
    {id:'EMP-1290',name:'Marcus Reid',role:'HR Manager',dept:'Human Resources',email:'marcus.reid@northwind.io',assets:1,status:'On Leave',joined:'2019-11-30'},
    {id:'EMP-1333',name:'Sofia Duarte',role:'Sales Director',dept:'Sales',email:'sofia.duarte@northwind.io',assets:3,status:'Active',joined:'2016-05-09'},
    {id:'EMP-1377',name:'Owen Clarke',role:'Logistics Lead',dept:'Logistics',email:'owen.clarke@northwind.io',assets:2,status:'Active',joined:'2020-10-14'},
    {id:'EMP-1401',name:'Hannah Cole',role:'Software Engineer',dept:'Engineering',email:'hannah.cole@northwind.io',assets:2,status:'Active',joined:'2022-04-25'},
    {id:'EMP-1455',name:'Ravi Kapoor',role:'Network Engineer',dept:'IT Operations',email:'ravi.kapoor@northwind.io',assets:3,status:'Active',joined:'2021-08-30'},
    {id:'EMP-1490',name:'Elena Rossi',role:'UX Researcher',dept:'Design',email:'elena.rossi@northwind.io',assets:1,status:'Active',joined:'2023-01-12'},
    {id:'EMP-1522',name:'Tom Fischer',role:'Field Technician',dept:'Facilities',email:'tom.fischer@northwind.io',assets:2,status:'Active',joined:'2020-06-18'},
  ],
  assets:[
    {id:'AST-90021',name:'MacBook Pro 16" M3 Max',tag:'NW-LT-0421',cat:'Laptops & Computers',status:'Allocated',dept:'Engineering',holder:'Hannah Cole',location:'Building A · Floor 3',value:3499,purchased:'2024-02-11',serial:'C02XK1YHJGH7',condition:'Excellent',warranty:'2027-02-11'},
    {id:'AST-90022',name:'Dell UltraSharp U3223QE',tag:'NW-MN-1180',cat:'Monitors & Displays',status:'Allocated',dept:'Engineering',holder:'Hannah Cole',location:'Building A · Floor 3',value:899,purchased:'2024-02-11',serial:'CN0X72YQ',condition:'Excellent',warranty:'2027-02-11'},
    {id:'AST-90023',name:'Cisco Catalyst 9300 Switch',tag:'NW-NW-0044',cat:'Networking Equipment',status:'Available',dept:'IT Operations',holder:'—',location:'Building B · Floor 1',value:6200,purchased:'2023-06-05',serial:'FDO2419A8XY',condition:'Good',warranty:'2028-06-05'},
    {id:'AST-90024',name:'Herman Miller Aeron Chair',tag:'NW-FN-2210',cat:'Office Furniture',status:'Allocated',dept:'Design',holder:'Lena Vargas',location:'Building A · Floor 2',value:1395,purchased:'2022-09-14',serial:'HM-AER-88213',condition:'Good',warranty:'2034-09-14'},
    {id:'AST-90025',name:'iPhone 15 Pro',tag:'NW-MB-3390',cat:'Mobile Devices',status:'Reserved',dept:'Sales',holder:'Sofia Duarte',location:'Building C · Floor 2',value:1199,purchased:'2024-01-20',serial:'DNPXK2Y8Q1',condition:'Excellent',warranty:'2026-01-20'},
    {id:'AST-90026',name:'Keysight Oscilloscope DSOX1204',tag:'NW-LB-0071',cat:'Lab & Test Equipment',status:'Maintenance',dept:'Engineering',holder:'—',location:'Lab · Room 12',value:2450,purchased:'2021-11-03',serial:'MY58230144',condition:'Fair',warranty:'2026-11-03'},
    {id:'AST-90027',name:'Ford Transit Cargo Van',tag:'NW-VH-0009',cat:'Vehicles',status:'Allocated',dept:'Logistics',holder:'Owen Clarke',location:'Warehouse · Bay 4',value:41800,purchased:'2022-03-28',serial:'1FTBW2CM5NK',condition:'Good',warranty:'2027-03-28'},
    {id:'AST-90028',name:'Logitech Rally Bar Conf. Cam',tag:'NW-AV-0052',cat:'AV & Conferencing',status:'Available',dept:'Facilities',holder:'—',location:'Building A · Conf 3B',value:3999,purchased:'2023-08-19',serial:'2129LZ0J4K',condition:'Excellent',warranty:'2026-08-19'},
    {id:'AST-90029',name:'Lenovo ThinkPad X1 Carbon',tag:'NW-LT-0512',cat:'Laptops & Computers',status:'Allocated',dept:'IT Operations',holder:'Ravi Kapoor',location:'Building B · Floor 1',value:2199,purchased:'2023-12-01',serial:'PF3XM9K2',condition:'Good',warranty:'2026-12-01'},
    {id:'AST-90030',name:'Aruba 6300M Access Point',tag:'NW-NW-0061',cat:'Networking Equipment',status:'Maintenance',dept:'IT Operations',holder:'—',location:'Building B · Floor 1',value:1750,purchased:'2022-07-15',serial:'CNF2K80112',condition:'Fair',warranty:'2027-07-15'},
    {id:'AST-90031',name:'Samsung 49" Odyssey G9',tag:'NW-MN-1244',cat:'Monitors & Displays',status:'Reserved',dept:'Design',holder:'Elena Rossi',location:'Building A · Floor 2',value:1299,purchased:'2024-03-08',serial:'0DXNHCM',condition:'Excellent',warranty:'2027-03-08'},
    {id:'AST-90032',name:'Standing Desk Pro 60"',tag:'NW-FN-2318',cat:'Office Furniture',status:'Available',dept:'Facilities',holder:'—',location:'Building B · Storage',value:749,purchased:'2023-05-22',serial:'SDP-60-4471',condition:'Good',warranty:'2028-05-22'},
    {id:'AST-90033',name:'iPad Pro 12.9" M2',tag:'NW-MB-3421',cat:'Mobile Devices',status:'Allocated',dept:'Design',holder:'Lena Vargas',location:'Building A · Floor 2',value:1099,purchased:'2023-10-11',serial:'GX7YK2M1Q',condition:'Excellent',warranty:'2025-10-11'},
    {id:'AST-90034',name:'HP Color LaserJet E85055',tag:'NW-OF-0188',cat:'Office Furniture',status:'Maintenance',dept:'Facilities',holder:'—',location:'Building A · Floor 2',value:4200,purchased:'2021-04-30',serial:'CNBRK4501Z',condition:'Fair',warranty:'2026-04-30'},
    {id:'AST-90035',name:'Dell Precision 7680 Mobile WS',tag:'NW-LT-0533',cat:'Laptops & Computers',status:'Available',dept:'Engineering',holder:'—',location:'Building A · Floor 3',value:3850,purchased:'2024-04-02',serial:'JKL9920MN',condition:'Excellent',warranty:'2027-04-02'},
  ],
  bookings:[
    {id:'BK-4471',asset:'Logitech Rally Bar Conf. Cam',resource:'Conference Room 3B',by:'Sofia Duarte',dept:'Sales',start:'2026-07-12 09:00',end:'2026-07-12 10:30',status:'Ongoing',color:'navy'},
    {id:'BK-4472',asset:'Ford Transit Cargo Van',resource:'Vehicle Fleet',by:'Owen Clarke',dept:'Logistics',start:'2026-07-12 13:00',end:'2026-07-12 18:00',status:'Upcoming',color:'copper'},
    {id:'BK-4473',asset:'Dell Precision 7680 WS',resource:'Lab Room 12',by:'Hannah Cole',dept:'Engineering',start:'2026-07-13 10:00',end:'2026-07-13 16:00',status:'Upcoming',color:'teal'},
    {id:'BK-4474',asset:'Samsung 49" Odyssey G9',resource:'Design Studio',by:'Elena Rossi',dept:'Design',start:'2026-07-14 09:30',end:'2026-07-14 12:00',status:'Upcoming',color:'navy'},
    {id:'BK-4468',asset:'Keysight Oscilloscope',resource:'Lab Room 12',by:'Daniel Okafor',dept:'Engineering',start:'2026-07-10 14:00',end:'2026-07-10 17:00',status:'Completed',color:'teal'},
    {id:'BK-4465',asset:'Conference Room 3B',resource:'Conference Room 3B',by:'Marcus Reid',dept:'HR',start:'2026-07-09 11:00',end:'2026-07-09 12:00',status:'Cancelled',color:'copper'},
  ],
  maintenance:[
    {id:'MT-2201',asset:'Keysight Oscilloscope DSOX1204',tag:'NW-LB-0071',issue:'Calibration drift on channel 2',priority:'High',tech:'Tom Fischer',stage:'in-progress',created:'2026-07-08',dept:'Engineering'},
    {id:'MT-2202',asset:'Aruba 6300M Access Point',tag:'NW-NW-0061',issue:'Intermittent packet loss, needs firmware',priority:'Medium',tech:'Ravi Kapoor',stage:'assigned',created:'2026-07-09',dept:'IT Operations'},
    {id:'MT-2203',asset:'HP Color LaserJet E85055',tag:'NW-OF-0188',issue:'Fuser unit replacement required',priority:'High',tech:'Tom Fischer',stage:'approved',created:'2026-07-10',dept:'Facilities'},
    {id:'MT-2204',asset:'MacBook Pro 16" M3 Max',tag:'NW-LT-0421',issue:'Battery service - swelling detected',priority:'Critical',tech:'—',stage:'pending',created:'2026-07-11',dept:'Engineering'},
    {id:'MT-2205',asset:'Standing Desk Pro 60"',tag:'NW-FN-2318',issue:'Motor makes grinding noise on lift',priority:'Low',tech:'—',stage:'pending',created:'2026-07-11',dept:'Facilities'},
    {id:'MT-2206',asset:'Cisco Catalyst 9300 Switch',tag:'NW-NW-0044',issue:'Port 14-18 not linking',priority:'Medium',tech:'Ravi Kapoor',stage:'in-progress',created:'2026-07-07',dept:'IT Operations'},
    {id:'MT-2207',asset:'Dell UltraSharp U3223QE',tag:'NW-MN-1180',issue:'Dead pixel cluster, warranty claim',priority:'Low',tech:'Priya Sharma',stage:'resolved',created:'2026-07-04',dept:'Engineering'},
    {id:'MT-2208',asset:'iPhone 15 Pro',tag:'NW-MB-3390',issue:'Cracked screen replacement',priority:'Medium',tech:'Tom Fischer',stage:'resolved',created:'2026-07-03',dept:'Sales'},
    {id:'MT-2209',asset:'Ford Transit Cargo Van',tag:'NW-VH-0009',issue:'Scheduled 20k service + brake pads',priority:'Medium',tech:'—',stage:'approved',created:'2026-07-10',dept:'Logistics'},
  ],
  audits:[
    {id:'AUD-08',name:'Q3 2026 Full Inventory Audit',auditor:'Priya Sharma',scope:'All Departments',total:1284,verified:947,missing:12,damaged:23,progress:76,status:'In Progress',due:'2026-07-31'},
    {id:'AUD-07',name:'Engineering Floor 3 Spot Check',auditor:'Aarav Mehta',scope:'Engineering',total:132,verified:132,missing:2,damaged:4,progress:100,status:'Completed',due:'2026-06-20'},
    {id:'AUD-06',name:'IT Data Center Assets',auditor:'Ravi Kapoor',scope:'IT Operations',total:298,verified:210,missing:1,damaged:3,progress:70,status:'In Progress',due:'2026-07-25'},
    {id:'AUD-05',name:'Vehicle Fleet Compliance',auditor:'Owen Clarke',scope:'Logistics',total:24,verified:24,missing:0,damaged:1,progress:100,status:'Completed',due:'2026-06-05'},
  ],
  notifications:[
    {id:1,type:'warning',icon:'wrench',title:'Critical maintenance raised',body:'MacBook Pro 16" (NW-LT-0421) flagged for battery swelling — needs immediate attention.',time:'12 min ago',unread:true,priority:'High'},
    {id:2,type:'info',icon:'transfer',title:'Transfer request pending approval',body:'Ravi Kapoor requested transfer of Cisco Catalyst 9300 to Data Center Rack 4.',time:'48 min ago',unread:true,priority:'Medium'},
    {id:3,type:'success',icon:'check2',title:'Audit milestone reached',body:'Q3 2026 Full Inventory Audit has passed 75% verification.',time:'2 hours ago',unread:true,priority:'Low'},
    {id:4,type:'warning',icon:'clock',title:'Overdue return',body:'iPad Pro 12.9" allocated to Lena Vargas is 3 days past its scheduled return date.',time:'5 hours ago',unread:false,priority:'High'},
    {id:5,type:'info',icon:'calendar',title:'Upcoming booking reminder',body:'Conference Room 3B is booked for the Sales sync at 09:00 tomorrow.',time:'Yesterday',unread:false,priority:'Low'},
    {id:6,type:'success',icon:'box',title:'New asset registered',body:'Dell Precision 7680 Mobile Workstation (NW-LT-0533) added to Engineering inventory.',time:'Yesterday',unread:false,priority:'Low'},
    {id:7,type:'danger',icon:'alert',title:'Discrepancy detected',body:'2 assets reported missing during Engineering Floor 3 spot check.',time:'2 days ago',unread:false,priority:'High'},
  ],
  activities:[
    {who:'Ravi Kapoor',action:'requested transfer of',target:'Cisco Catalyst 9300',time:'12m',dot:'copper'},
    {who:'Priya Sharma',action:'completed audit stage for',target:'Engineering Floor 3',time:'1h',dot:'success'},
    {who:'Tom Fischer',action:'started maintenance on',target:'Keysight Oscilloscope',time:'3h',dot:'navy'},
    {who:'Aarav Mehta',action:'registered new asset',target:'Dell Precision 7680',time:'5h',dot:'navy'},
    {who:'Sofia Duarte',action:'booked',target:'Conference Room 3B',time:'6h',dot:'copper'},
    {who:'Hannah Cole',action:'returned',target:'Dell UltraSharp U3223QE',time:'Yesterday',dot:'success'},
  ],
  approvals:[
    {title:'Asset Transfer — Cisco Catalyst 9300',by:'Ravi Kapoor',dept:'IT Operations',type:'Transfer'},
    {title:'Maintenance Approval — MacBook Pro 16"',by:'Hannah Cole',dept:'Engineering',type:'Maintenance'},
    {title:'Booking Request — Vehicle Fleet',by:'Owen Clarke',dept:'Logistics',type:'Booking'},
    {title:'Asset Write-off — HP LaserJet E85055',by:'Priya Sharma',dept:'Facilities',type:'Disposal'},
  ],
};

/* Chart datasets */
const CHARTS = {
  utilization:[62,68,71,65,74,78,82,79,85,88,84,90],
  utilLabels:['Aug','Sep','Oct','Nov','Dec','Jan','Feb','Mar','Apr','May','Jun','Jul'],
  maintenance:[{m:'Feb',v:14},{m:'Mar',v:22},{m:'Apr',v:18},{m:'May',v:27},{m:'Jun',v:19},{m:'Jul',v:24}],
  allocByCat:[{l:'Laptops',v:412,c:'#1B365D'},{l:'Furniture',v:534,c:'#B87333'},{l:'Monitors',v:288,c:'#2F3E46'},{l:'Mobile',v:196,c:'#3d8a80'},{l:'Network',v:96,c:'#5b6b76'},{l:'Other',v:154,c:'#b7bcc2'}],
  statusSplit:[{l:'Allocated',v:842,c:'#1B365D'},{l:'Available',v:486,c:'#3d8a80'},{l:'Maintenance',v:124,c:'#B87333'},{l:'Reserved',v:228,c:'#5b6b76'}],
  deptAssets:[{l:'IT Ops',v:298},{l:'Facilities',v:210},{l:'Logistics',v:174},{l:'Engineering',v:132},{l:'Sales',v:120},{l:'Finance',v:71}],
  bookingTrend:[24,31,28,42,38,45,52,48,55,61,58,67],
};
